export const LANGUAGES = {
    auto: { name: 'Detectar idioma', native: 'Detectar', flag: '🌐' },
    af: { name: 'Afrikaans', native: 'Afrikaans', flag: '🇿🇦' },
    sq: { name: 'Albanian', native: 'Shqip', flag: '🇦🇱' },
    am: { name: 'Amharic', native: 'አማርኛ', flag: '🇪🇹' },
    ar: { name: 'Arabic', native: 'العربية', flag: '🇸🇦' },
    hy: { name: 'Armenian', native: 'Հայերեն', flag: '🇦🇲' },
    az: { name: 'Azerbaijani', native: 'Azərbaycan', flag: '🇦🇿' },
    eu: { name: 'Basque', native: 'Euskara', flag: '🇪🇸' },
    be: { name: 'Belarusian', native: 'Беларуская', flag: '🇧🇾' },
    bn: { name: 'Bengali', native: 'বাংলা', flag: '🇧🇩' },
    bs: { name: 'Bosnian', native: 'Bosanski', flag: '🇧🇦' },
    bg: { name: 'Bulgarian', native: 'Български', flag: '🇧🇬' },
    my: { name: 'Burmese', native: 'မြန်မာဘာသာ', flag: '🇲🇲' },
    ca: { name: 'Catalan', native: 'Català', flag: '🇪🇸' },
    ceb: { name: 'Cebuano', native: 'Cebuano', flag: '🇵🇭' },
    ny: { name: 'Chichewa', native: 'Chichewa', flag: '🇲🇼' },
    zh: { name: 'Chinese (Simplified)', native: '简体中文', flag: '🇨🇳' },
    zh_TW: { name: 'Chinese (Traditional)', native: '繁體中文', flag: '🇹🇼' },
    co: { name: 'Corsican', native: 'Corsu', flag: '🇫🇷' },
    hr: { name: 'Croatian', native: 'Hrvatski', flag: '🇭🇷' },
    cs: { name: 'Czech', native: 'Čeština', flag: '🇨🇿' },
    da: { name: 'Danish', native: 'Dansk', flag: '🇩🇰' },
    nl: { name: 'Dutch', native: 'Nederlands', flag: '🇳🇱' },
    en: { name: 'English', native: 'English', flag: '🇬🇧' },
    eo: { name: 'Esperanto', native: 'Esperanto', flag: '🌍' },
    et: { name: 'Estonian', native: 'Eesti', flag: '🇪🇪' },
    tl: { name: 'Filipino', native: 'Filipino', flag: '🇵🇭' },
    fi: { name: 'Finnish', native: 'Suomi', flag: '🇫🇮' },
    fr: { name: 'French', native: 'Français', flag: '🇫🇷' },
    gl: { name: 'Galician', native: 'Galego', flag: '🇪🇸' },
    ka: { name: 'Georgian', native: 'ქართული', flag: '🇬🇪' },
    de: { name: 'German', native: 'Deutsch', flag: '🇩🇪' },
    el: { name: 'Greek', native: 'Ελληνικά', flag: '🇬🇷' },
    gu: { name: 'Gujarati', native: 'ગુજરાતી', flag: '🇮🇳' },
    ht: { name: 'Haitian Creole', native: 'Kreyòl Ayisyen', flag: '🇭🇹' },
    ha: { name: 'Hausa', native: 'Hausa', flag: '🇳🇬' },
    haw: { name: 'Hawaiian', native: 'Hawaiʻi', flag: '🇺🇸' },
    he: { name: 'Hebrew', native: 'עברית', flag: '🇮🇱' },
    hi: { name: 'Hindi', native: 'हिन्दी', flag: '🇮🇳' },
    hmn: { name: 'Hmong', native: 'Hmong', flag: '🇨🇳' },
    hu: { name: 'Hungarian', native: 'Magyar', flag: '🇭🇺' },
    is: { name: 'Icelandic', native: 'Íslenska', flag: '🇮🇸' },
    ig: { name: 'Igbo', native: 'Igbo', flag: '🇳🇬' },
    id: { name: 'Indonesian', native: 'Bahasa Indonesia', flag: '🇮🇩' },
    ga: { name: 'Irish', native: 'Gaeilge', flag: '🇮🇪' },
    it: { name: 'Italian', native: 'Italiano', flag: '🇮🇹' },
    ja: { name: 'Japanese', native: '日本語', flag: '🇯🇵' },
    jw: { name: 'Javanese', native: 'Basa Jawa', flag: '🇮🇩' },
    kn: { name: 'Kannada', native: 'ಕನ್ನಡ', flag: '🇮🇳' },
    kk: { name: 'Kazakh', native: 'Қазақ', flag: '🇰🇿' },
    km: { name: 'Khmer', native: 'ភាសាខ្មែរ', flag: '🇰🇭' },
    rw: { name: 'Kinyarwanda', native: 'Ikinyarwanda', flag: '🇷🇼' },
    ko: { name: 'Korean', native: '한국어', flag: '🇰🇷' },
    ku: { name: 'Kurdish (Kurmanji)', native: 'Kurdî', flag: '🇹🇷' },
    ky: { name: 'Kyrgyz', native: 'Кыргызча', flag: '🇰🇬' },
    lo: { name: 'Lao', native: 'ລາວ', flag: '🇱🇦' },
    la: { name: 'Latin', native: 'Latina', flag: '🇻🇦' },
    lv: { name: 'Latvian', native: 'Latviešu', flag: '🇱🇻' },
    lt: { name: 'Lithuanian', native: 'Lietuvių', flag: '🇱🇹' },
    lb: { name: 'Luxembourgish', native: 'Lëtzebuergesch', flag: '🇱🇺' },
    mk: { name: 'Macedonian', native: 'Македонски', flag: '🇲🇰' },
    mg: { name: 'Malagasy', native: 'Malagasy', flag: '🇲🇬' },
    ms: { name: 'Malay', native: 'Bahasa Melayu', flag: '🇲🇾' },
    ml: { name: 'Malayalam', native: 'മലയാളം', flag: '🇮🇳' },
    mt: { name: 'Maltese', native: 'Malti', flag: '🇲🇹' },
    mi: { name: 'Maori', native: 'Te Reo Māori', flag: '🇳🇿' },
    mr: { name: 'Marathi', native: 'मराठी', flag: '🇮🇳' },
    mn: { name: 'Mongolian', native: 'Монгол', flag: '🇲🇳' },
    ne: { name: 'Nepali', native: 'नेपाली', flag: '🇳🇵' },
    no: { name: 'Norwegian', native: 'Norsk', flag: '🇳🇴' },
    or: { name: 'Odia (Oriya)', native: 'ଓଡ଼ିଆ', flag: '🇮🇳' },
    ps: { name: 'Pashto', native: 'پښتو', flag: '🇦🇫' },
    fa: { name: 'Persian', native: 'فارسی', flag: '🇮🇷' },
    pl: { name: 'Polish', native: 'Polski', flag: '🇵🇱' },
    pt: { name: 'Portuguese', native: 'Português', flag: '🇵🇹' },
    pa: { name: 'Punjabi', native: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
    ro: { name: 'Romanian', native: 'Română', flag: '🇷🇴' },
    ru: { name: 'Russian', native: 'Русский', flag: '🇷🇺' },
    sm: { name: 'Samoan', native: 'Gagana Samoa', flag: '🇼🇸' },
    gd: { name: 'Scottish Gaelic', native: 'Gàidhlig', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
    sr: { name: 'Serbian', native: 'Српски', flag: '🇷🇸' },
    st: { name: 'Sesotho', native: 'Sesotho', flag: '🇱🇸' },
    sn: { name: 'Shona', native: 'Shona', flag: '🇿🇼' },
    sd: { name: 'Sindhi', native: 'سنڌي', flag: '🇵🇰' },
    si: { name: 'Sinhala', native: 'සිංහල', flag: '🇱🇰' },
    sk: { name: 'Slovak', native: 'Slovenčina', flag: '🇸🇰' },
    sl: { name: 'Slovenian', native: 'Slovenščina', flag: '🇸🇮' },
    so: { name: 'Somali', native: 'Soomaali', flag: '🇸🇴' },
    es: { name: 'Spanish', native: 'Español', flag: '🇪🇸' },
    su: { name: 'Sundanese', native: 'Basa Sunda', flag: '🇮🇩' },
    sw: { name: 'Swahili', native: 'Kiswahili', flag: '🇰🇪' },
    sv: { name: 'Swedish', native: 'Svenska', flag: '🇸🇪' },
    tg: { name: 'Tajik', native: 'Тоҷикӣ', flag: '🇹🇯' },
    ta: { name: 'Tamil', native: 'தமிழ்', flag: '🇮🇳' },
    tt: { name: 'Tatar', native: 'Татар', flag: '🇷🇺' },
    te: { name: 'Telugu', native: 'తెలుగు', flag: '🇮🇳' },
    th: { name: 'Thai', native: 'ไทย', flag: '🇹🇭' },
    tr: { name: 'Turkish', native: 'Türkçe', flag: '🇹🇷' },
    tk: { name: 'Turkmen', native: 'Türkmen', flag: '🇹🇲' },
    uk: { name: 'Ukrainian', native: 'Українська', flag: '🇺🇦' },
    ur: { name: 'Urdu', native: 'اردو', flag: '🇵🇰' },
    ug: { name: 'Uyghur', native: 'ئۇيغۇرچە', flag: '🇨🇳' },
    uz: { name: 'Uzbek', native: 'Oʻzbek', flag: '🇺🇿' },
    vi: { name: 'Vietnamese', native: 'Tiếng Việt', flag: '🇻🇳' },
    cy: { name: 'Welsh', native: 'Cymraeg', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
    xh: { name: 'Xhosa', native: 'isiXhosa', flag: '🇿🇦' },
    yi: { name: 'Yiddish', native: 'ייִדיש', flag: '🇮🇱' },
    yo: { name: 'Yoruba', native: 'Yorùbá', flag: '🇳🇬' },
    zu: { name: 'Zulu', native: 'isiZulu', flag: '🇿🇦' },
};

export function getLanguageCodes() {
    return Object.keys(LANGUAGES);
}

export function getLanguageInfo(code) {
    return LANGUAGES[code] || null;
}

export function getLanguageName(code) {
    return LANGUAGES[code]?.name || code;
}

export function getNativeName(code) {
    return LANGUAGES[code]?.native || code;
}

export function getLanguageFlag(code) {
    return LANGUAGES[code]?.flag || '🌐';
}
